import {StyleSheet} from 'react-native';
import {SizeConfig} from '../../size';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerConatiner: {
    width: SizeConfig.width * 100,
    borderBottomLeftRadius: SizeConfig.width * 6,
    borderBottomRightRadius: SizeConfig.width * 6,
    paddingVertical: SizeConfig.height * 1.6,
    paddingHorizontal: SizeConfig.width * 4,
  },
  appbarHome: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logImage: {
    width: SizeConfig.width * 25,
    resizeMode: 'contain',
    height: SizeConfig.height * 6,
  },
  logImage1: {
    width: SizeConfig.width * 33,
    resizeMode: 'contain',
    height: SizeConfig.height * 6,
  },

  offericonImage: {
    width: SizeConfig.width * 3,
    height: SizeConfig.height * 1.5,
    objectFit: 'contain',
  },
  offerText: {
    fontSize: SizeConfig.width * 3.2,
    color: '#3232C1',
    fontFamily: 'Outfit-Medium',
    fontWeight: '500',
    textAlign: 'center',
  },
  offerZone: {
    flexDirection: 'row',
    alignContent: 'center',
    alignItems: 'center',
    marginBottom: SizeConfig.height * 1,
  },
  offerZoneContainer: {
    borderColor: '#CDCDCD',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0,
    elevation: 1.5,
    shadowRadius: 0.5,
    borderRadius: SizeConfig.width * 2,
    flexDirection: 'row',
    borderWidth: SizeConfig.width * 0.2,
    paddingHorizontal: SizeConfig.width * 2.5,
    paddingVertical: SizeConfig.width * 0.6,
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    marginHorizontal: SizeConfig.width * 2,
  },
  offerLine: {
    width: SizeConfig.width * 5,
    objectFit: 'contain',
    flex: 1,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: SizeConfig.width * 4,
    paddingHorizontal: SizeConfig.width * 3,
    borderColor: '#FFFFFF',
    borderWidth: SizeConfig.width * 0.3,
    height: SizeConfig.height * 5.5,
  },
  searchInput: {
    flex: 1,
    paddingVertical: SizeConfig.height * 1,
    fontSize: SizeConfig.width * 4,
    color: '#1E1E1E',
  },

  searchIcon: {
    width: SizeConfig.width * 4,
    height: SizeConfig.width * 4,
    objectFit: 'contain',
  },
  overlay: {
    position: 'relative',
    top: SizeConfig.height * -5,
  },

  Imagescontainer: {
    position: 'absolute',
    top: -5,
    flexDirection: 'row',
  },
  leftImage: {
    width: SizeConfig.width * 50,
    resizeMode: 'cover',
    height: SizeConfig.height * 10,
  },
  rightImage: {
    width: SizeConfig.width * 50,
    resizeMode: 'cover',
    height: SizeConfig.height * 10,
  },
  homeBannerCarsoleMainConatiner: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    height: SizeConfig.height * 30,
    width: SizeConfig.width * 100,
  },
  homeBannerCarsole: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    height: SizeConfig.height * 27,
    width: SizeConfig.width * 100,
  },
  homeBannerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'red',
  },
  homeBanner: {
    width: '100%',
    height: '100%',
  },
  activePaginationData: {
    color: '#C2C1FF',
    width: SizeConfig.width * 4,
    height: SizeConfig.width * 4,
    borderRadius: 4,
    marginHorizontal: SizeConfig.width * 1,
  },
  inactivePaginationData: {
    color: '#98989A',
    width: SizeConfig.width * 3,
    height: SizeConfig.width * 3,
    borderRadius: 3,
    marginHorizontal: SizeConfig.width * 1,
  },
  categoryListContainer: {
    // paddingHorizontal: SizeConfig.width * 3,
    // marginTop: SizeConfig.height * 0,
    alignItems: 'center',
    position: 'relative',
    top: SizeConfig.height * -13,
  },
  categoryCard: {
    paddingVertical: SizeConfig.height * 1.2,
    borderRadius: SizeConfig.width * 3.5,
    backgroundColor: 'white',
    paddingHorizontal: SizeConfig.width * 4.5,
    marginVertical: SizeConfig.height * 1,
    marginRight: SizeConfig.width * 0.5,
    marginLeft: SizeConfig.width * 2.8,
    shadowColor: '#000',
    shadowOffset: {
      width: 5,
      height: 4,
    },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 2,
    textAlign: 'center',
  },
  categoryText: {
    fontSize: SizeConfig.width * 4.2,
    color: '#4C4C4C',
    fontFamily: 'Outfit-Bold',
    fontWeight: '800',
    textAlign: 'center',
  },

  typeCategoryListContainer: {
    alignItems: 'center',
    paddingHorizontal: SizeConfig.width * 3,
    marginVertical: SizeConfig.height * 1.5,
  },
  typeCategoryContainer: {
    alignItems: 'center',
    marginBottom: SizeConfig.height * 1,
    marginHorizontal: SizeConfig.width * 2.5,
    alignContent: 'center',
    justifyContent: 'center',
  },
  typeCategoryCircle: {
    alignItems: 'center',
    width: SizeConfig.width * 14,
    height: SizeConfig.width * 14,
    borderRadius: SizeConfig.width * 5,
    backgroundColor: '#D7D7FF',
    alignContent: 'center',
    justifyContent: 'center',
    marginBottom: SizeConfig.height * 0.7,
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 1,
    shadowRadius: 2.5,
    elevation: 6,
    borderWidth: SizeConfig.width * 0.6,
    borderColor: '#FFFFFF',
  },
  categoryImage: {
    width: SizeConfig.width * 10,
    height: SizeConfig.width * 10,
    objectFit: 'contain',
  },

  typeSubText: {
    color: '#0B0B0B',
    fontFamily: 'Outfit-Medium',
    fontWeight: '500',
    fontSize: SizeConfig.width * 3.6,
  },

  longLineImag: {
    width: SizeConfig.width * 100,
    objectFit: 'contain',
    flex: 1,
  },

  cardsHeaderText: {
    color: '#000000',
    fontFamily: 'Outfit-Medium',
    fontWeight: '500',
    fontSize: SizeConfig.width * 4.5,
    paddingHorizontal: SizeConfig.width * 6,
    paddingTop: SizeConfig.height * 1,
    paddingBottom: SizeConfig.height,
  },

  // popularCardsConatiner: {
  //   borderRadius: SizeConfig.width * 5,
  //   width: '100%',
  //   borderColor: '#E7E7E7',
  //   borderWidth: SizeConfig.width * 0.3,
  //   paddingVertical: SizeConfig.height * 2,
  //   paddingHorizontal: SizeConfig.width * 2,
  //   alignItems: 'center',
  //   backgroundColor: 'white',
  //   shadowColor: '#000000',
  //   shadowOffset: {width: 0, height: 0},
  //   shadowOpacity: 0.5,
  //   shadowRadius: 2,
  //   elevation: 0.5,
  //   height: SizeConfig.height * 15,
  //   alignContent: 'center',
  // },
  // popularCardsImage: {
  //   borderRadius: SizeConfig.width * 6,
  //   objectFit: 'contain',
  //   height: '100%',
  //   width: '100%',
  // },
  // popularCardHeader: {
  //   color: '#000073',
  //   fontFamily: 'Outfit-SemiBold',
  //   fontWeight: '700',
  //   fontSize: SizeConfig.width * 4.2,
  //   paddingTop: SizeConfig.height * 1.5,
  //   paddingLeft: SizeConfig.width,
  // },
  // popularCardSubHeader: {
  //   color: '#000000',
  //   fontFamily: 'Outfit-SemiBold',
  //   fontWeight: '700',
  //   fontSize: SizeConfig.width * 3.5,
  // },
  // popularCardPrice: {
  //   color: '#000000',
  //   fontFamily: 'Outfit-Medium',
  //   fontWeight: '600',
  //   fontSize: SizeConfig.width * 4,
  //   textAlign: 'right',
  //   paddingLeft: SizeConfig.width,
  // },

  popularCardMainContainer: {
    width: SizeConfig.width * 60,
    marginLeft: SizeConfig.width * 2.8,
    marginBottom: SizeConfig.height * 2,

    alignItems: 'flex-start',
    // height: SizeConfig.height * 25,
  },
  popularCardsContainer: {
    width: '100%',
    overflow: 'hidden',
    height: SizeConfig.height * 18,
    borderColor: '#E7E7E7',
    borderWidth: SizeConfig.width * 0.3,
    borderRadius: SizeConfig.width * 3.5,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 0.5,
  },
  popularCardsImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  textContainer: {
    // paddingVertical: SizeConfig.height * 1,
    paddingHorizontal: SizeConfig.width * 1.5,
    width: '100%',
    // height: SizeConfig.height * 7,
    overflow: 'hidden',
  },
  popularCardHeader: {
    color: '#000000',
    fontFamily: 'Outfit-Medium',
    fontWeight: '500',
    fontSize: SizeConfig.width * 4,
    paddingTop: SizeConfig.height * 0.6,
  },
  popularCardPrice: {
    color: '#6663ff',
    fontFamily: 'Outfit-SemiBold',
    fontWeight: '600',
    fontSize: SizeConfig.width * 4,
    paddingHorizontal: SizeConfig.width * 1,
  },

  popularExPrice: {
    color: '#0B8C00',
    fontFamily: 'Outfit-Regular',
    fontWeight: '400',
    fontSize: SizeConfig.width * 4,
    paddingHorizontal: SizeConfig.width * 1,
    alignItems: 'center',
  },
  popularCardContainer: {
    flexDirection: 'row',

    position: 'absolute',
    bottom: 0,
  },

  subCardsMainConatiner: {
    flex: 1,
    paddingLeft: SizeConfig.width * 3,
    paddingRight: SizeConfig.width * 3,
    justifyContent: 'space-between',
    paddingVertical: SizeConfig.height * 0.5,
  },

  subCardsConatiner: {
    borderRadius: SizeConfig.width * 4,
    paddingTop: SizeConfig.height * 0.5,
    paddingBottom: SizeConfig.height * 1.2,
    paddingHorizontal: SizeConfig.width * 2,
    borderColor: '#F3F3F3',
    borderWidth: SizeConfig.width * 0.4,
    alignItems: 'center',
    backgroundColor: '#F4F4FF',
    width: '31.33%',
    marginBottom: SizeConfig.width * 2,
    marginRight: SizeConfig.width * 1.5,
    marginLeft: SizeConfig.width * 0.5,
  },
  subCardHeader: {
    color: '#000000',
    fontFamily: 'Outfit-Regular',
    fontWeight: '400',
    fontSize: SizeConfig.width * 4,
    textAlign: 'center',
  },
  subCardsImage: {
    resizeMode: 'contain',
    height: SizeConfig.height * 10,
    width: '100%',
  },
  flatListContent: {
    justifyContent: 'space-between',
  },
  reviewConatiner: {
    borderRadius: SizeConfig.width * 5,
    width: SizeConfig.width * 85,
    height: SizeConfig.height * 22,
    marginLeft: SizeConfig.width * 3.8,
    overflow: 'hidden',
    backgroundColor: 'white',
  },
  reviewCardsImage: {
    resizeMode: 'contain',
    height: '100%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewCardsPlayerImage: {
    resizeMode: 'contain',
    width: SizeConfig.width * 40,
    alignSelf: 'center',
  },
  reviewCardsPlayerText: {
    color: '#FFFFFF',
    fontFamily: 'Outfit-Medium',
    fontWeight: '500',
    fontSize: SizeConfig.width * 4,
    textAlign: 'left',
    position: 'absolute',
    top: SizeConfig.height * 1.6,
    left: SizeConfig.width * 4,
  },

  bannersImagescontainer: {
    width: SizeConfig.width * 100,
    height: SizeConfig.height * 10,
    borderColor: 'white',
    borderWidth: SizeConfig.width * 0.3,
    backgroundColor: '#F1F1F7',
    borderRadius: SizeConfig.width * 3,
    paddingVertical: SizeConfig.width * 1.5,
    paddingLeft: SizeConfig.width * 5,
    paddingRight: SizeConfig.width * 3,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0,
    elevation: 2,
    shadowRadius: 0.5,
    justifyContent: 'space-between',
  },

  bennerLogo: {
    width: SizeConfig.width * 15,
    height: SizeConfig.width * 15,
    objectFit: 'contain',
  },
  textBannerContainer: {
    marginHorizontal: SizeConfig.width * 4,
    alignItems: 'flex-start',
    width: '50%',
  },
  BannnerCardHeader: {
    color: '#000000',
    fontFamily: 'Outfit-SemiBold',
    fontWeight: '600',
    fontSize: SizeConfig.width * 3.7,
  },
  BannnerSubCardHeader: {
    color: '#000000',
    fontFamily: 'Outfit-SemiBold',
    fontWeight: '600',
    fontSize: SizeConfig.width * 3.6,
    paddingTop: SizeConfig.height * 0.1,
  },
  bannerButtonConatiner: {
    borderRadius: SizeConfig.width * 3,
    paddingVertical: SizeConfig.width * 0.5,
    paddingHorizontal: SizeConfig.width * 3,
    backgroundColor: '#1E2839',

    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
  },
  bannerButtonText: {
    color: '#FFFFFF',
    fontFamily: 'Outfit-SemiBold',
    fontWeight: '600',
    fontSize: SizeConfig.width * 2.8,
  },
  dividerContainerZone: {
    flexDirection: 'row',
    alignContent: 'center',
    alignItems: 'center',

    paddingHorizontal: SizeConfig.width * 3,
  },
  gridCardsHeaderText: {
    color: '#000000',
    fontFamily: 'Outfit-Regular',
    fontWeight: '400',
    fontSize: SizeConfig.width * 5,
    paddingHorizontal: SizeConfig.width * 2,
  },
  gridSubCardsHeaderText: {
    color: '#3232C1',
    fontFamily: 'Outfit-Regular',
    fontWeight: '400',
    fontSize: SizeConfig.width * 3.8,
    paddingBottom: SizeConfig.height * 1,
    paddingTop: SizeConfig.height * 0.5,
    textAlign: 'center',
  },
  popularCardHeaderTwo: {
    color: '#000000',
    fontFamily: 'Outfit-Regular',
    fontWeight: '400',
    fontSize: SizeConfig.width * 4,
    paddingTop: SizeConfig.height * 0.6,
  },
});
